module.exports = {
  title: {
    designSystem: "Design System",
    components: "Components",
    atoms: "Atoms",
    molecules: "Molecules",
    organisms: "Organisms",
    templates: "Templates",
    pages: "Pages",
    tokens: "Tokens",
    utils: "Utils",
    typography: "Typography",
    gridSystem: "Grid system",
    forms: "Forms",
    colours: "Colours",
    spacing: "Spacing",
    lab: "Lab",
    latestVersion: "Latest version",
  },
  heading: {
    lab: "\n\n ## Lab",
    basicRules: "### Basic rules",
    details: "#### Details",
  },
};
