module.exports = {
  title: {
    designSystem: "Design System",
    components: "Components",
    atoms: "Atoms",
    molecules: "Molecules",
    organisms: "Organisms",
    templates: "Templates",
    pages: "Pages",
    tokens: "Tokens",
    utils: "Utils",
    typography: "Typography",
    gridSystem: "Grid system",
    flex: "Flex",
    forms: "Forms",
    colours: "Colours",
    ratio: "Ratio",
    round: "Round",
    spacing: "Spacing",
    width: "Width",
    lab: "Lab",
    defaultStory: "Default",
    latestVersion: "Latest version",
    themes: "Themes (beta)",
  },
  heading: {
    lab: "\n\n ## Lab",
    default: "\n\n ## Default",
    basicRules: "### Basic rules",
    details: "#### Details",
  },
};
