name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # Build design-system homepage
  #
  homepage:
    name: "Verify that the homepage builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v4

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.0'
          cache: 'npm'

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i
        working-directory: homepage

      #
      # Step 4
      #
      - name: Build NPM Package
        run: npm run build
        working-directory: homepage

  #
  # Build Storybook from source
  #
  storybook:
    name: "Verify that Storybook builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v4

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.0'
          cache: 'npm'

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 4
      #
      - name: Build StoryBook
        run: npm run storybook:build


  #
  # Build CDN Distribution from source
  #
  distribution:
    name: "Verify that the CDN distribution builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v4

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.0'
          cache: 'npm'

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 4
      #
      - name: Build Distribution
        run: npm run dist:build:prod


  #
  # Build NPM Package from source
  #
  package:
    name: "Verify that the NPM package builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v4

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '16.19.0'
          cache: 'npm'

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 4
      #
      - name: Build NPM Package
        run: npm run package:build:prod
