name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  storybook:
    name: "Verify that Storybook builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      # Set up job
      #
      - name: Checkout
        uses: actions/checkout@v2

      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 2
      # Cache Management
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })

      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-storybook-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-storybook-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-storybook-


      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i


      #
      # Step 4
      #
      - name: Build StoryBook
        run: npm run storybook:build


  distribution:
    name: "Verify that the distribution builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      # Set up job
      #
      - name: Checkout
        uses: actions/checkout@v2

      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 2
      # Cache Management
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-distribution-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-distribution-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-distribution-

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 4
      #
      - name: Build Distribution
        run: npm run dist:build:prod


  package:
    name: "Verify that the NPM package builds correctly"
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:

      #
      # Step 1
      # Set up job
      #
      - name: Checkout
        uses: actions/checkout@v2

      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 2
      # Cache Management
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-package-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-package-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-package-

      #
      # Step 3
      #
      - name: Initialise NPM
        run: npm i


      #
      # Step 4
      #
      - name: Build NPM Package
        run: npm run package:build:prod
