name: Release Workflow

on:
  release:
    types: [published]

jobs:
  #
  # Build homepage distribution from source
  #
  build_homepage:
    name: "Build Homepage Distribution"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 3
      # Cache Management (CDN Distribution)
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-homepage-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-homepage-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-homepage-

      #
      # Step 4
      #
      - name: Initialise NPM
        run: npm i
        working-directory: homepage

      #
      # Step 5
      #
      - name: Build dist folder
        run: npm run build
        working-directory: homepage

      #
      # Step 6
      # Store homepage distribution workflow artifacts
      #
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: homepage-dist
          path: homepage/dist/

  #
  # Build CDN Distribution from source
  #
  build_dist:
    name: "Build CDN Distribution"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 3
      # Cache Management (CDN Distribution)
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-distribution-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-distribution-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-distribution-

      #
      # Step 4
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 5
      #
      - name: Build dist folder
        run: npm run dist:build:prod

      #
      # Step 6
      # Store CDN distribution workflow artifacts
      #
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cdn-dist
          path: |
            dist/fonts/
            dist/icons/
            dist/images/
            dist/scripts/
            dist/static/
            dist/stylesheets/

  #
  # Build Storybook from source
  #
  build_storybook:
    name: "Build Storybook Distribution"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 3
      # Cache Management (Storybook)
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-storybook-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-storybook-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-storybook-

      #
      # Step 4
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 7
      # Build storybook project
      #
      - name: Build Storybook
        env:
          STORYBOOK_VERSION: ${{ github.event.release.tag_name }}
        run: npm run storybook:build

      #
      # Step 8
      # Store Storybook workflow artifacts
      #
      - name: Archive storybook artifact
        uses: actions/upload-artifact@v2
        with:
          name: storybook-dist
          path: storybook-static/

  #
  # Build NPM Package from source
  #
  build_npm_package:
    name: "Build NPM Distribution"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      #
      # Step 1
      # Checkout the project's sourcecode
      #
      - name: Checkout
        uses: actions/checkout@v2

      #
      # Step 2
      # Set Node.js version
      #
      - name: Request Node Version
        uses: actions/setup-node@v2
        with:
          node-version: '12.6.0'

      #
      # Step 3
      # Cache Management (NPM package)
      #
      - name: Get cache key helper values
        uses: actions/github-script@v3
        id: cache-key-helper
        with:
          result-encoding: string
          script: |
            return JSON.stringify({
              "year" : new Date().getFullYear(),
              "rotation" : new Date().getTimezoneOffset()
            })
      - name: Setup cache (Node.js packages)
        uses: actions/cache@v2
        env:
          YEAR: ${{ fromJSON(steps.cache-key-helper.outputs.result).year }}
          ROTATION: ${{ fromJSON(steps.cache-key-helper.outputs.result).rotation }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-nhs-digital-npm-${{ env.YEAR }}-${{ env.ROTATION }}
          restore-keys: |
            ${{ runner.os }}-nhs-digital-npm-${{ env.YEAR }}-
            ${{ runner.os }}-nhs-digital-npm-

      #
      # Step 4
      #
      - name: Initialise NPM
        run: npm i

      #
      # Step 5
      #
      - name: Build NPM
        run: npm run package:build:prod

      #
      # Step 6
      # Store NPM Package workflow artifacts
      #
      - name: Archive NPM package artifact
        uses: actions/upload-artifact@v2
        with:
          name: npm-dist
          path: |
            package/

  add_release_assets:
    name: "Add release assets"
    needs:
      - build_homepage
      - build_dist
      - build_storybook
      - build_npm_package
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      #
      # Step 1
      #
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          path: workflow-artifacts

      #
      # Step 2
      #
      - name: Read version
        id: version
        run: |
          echo "::set-output name=version::$(cat ${{steps.download.outputs.download-path}}/version/version)"
      #
      # Step 3
      # Zip up each build artifacts with it's version number injected.
      #

      #
      # Step 3.1
      #
      - name: Zip CDN distribution
        run: |
          echo ${{ steps.version.outputs.version }} > version
          zip -r ../cdn-dist.zip .
        working-directory: ${{steps.download.outputs.download-path}}/cdn-dist

      #
      # Step 3.2
      #
      - name: Zip storybook distribution
        run: |
          echo ${{ steps.version.outputs.version }} > version
          zip -r ../storybook.zip .
        working-directory: ${{steps.download.outputs.download-path}}/storybook-dist

      #
      # Step 3.3
      #
      - name: Zip NPM package distribution
        run: |
          echo ${{ steps.version.outputs.version }} > version
          zip -r ../npm-dist.zip .
        working-directory: ${{steps.download.outputs.download-path}}/npm-dist

      #
      # Step 3.4
      #
      - name: Zip Homepage distribution
        run: |
          echo ${{ steps.version.outputs.version }} > version
          zip -r ../homepage-dist.zip .
        working-directory: ${{steps.download.outputs.download-path}}/homepage-dist

      #
      # Step 4
      # Add release assets
      # - Adds dist, storybook and package to the release
      #
      - name: Upload Homepage Dist Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path:  ${{steps.download.outputs.download-path}}/homepage-dist.zip
          asset_name: homepage-dist-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload CDN Dist Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path:  ${{steps.download.outputs.download-path}}/cdn-dist.zip
          asset_name: cdn-dist-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload Storybook Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path:  ${{steps.download.outputs.download-path}}/storybook.zip
          asset_name: storybook-dist-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip

      - name: Upload NPM Package Zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path:  ${{steps.download.outputs.download-path}}/npm-dist.zip
          asset_name: npm-dist-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip

  #
  # Put CDN distribution artifact onto the S3 origin.
  #
  dist_cdn:
    name: "Distribute CDN"
    needs:
      - build_dist
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      #
      # Step 1
      # Download CDN artifact and merge version artifact into the same folder
      #
      - name: Download CDN artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: cdn-dist
          path: cdn-dist

      #
      # Step 2
      # Set up AWS CLI
      #
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      #
      # Step 3
      # Replace 'latest' folder's content
      #
      - name: Replace latest
        working-directory: ${{steps.download.outputs.download-path}}
        run: aws s3 sync . s3://${{ secrets.S3_ORIGIN }}/cdn/latest --delete

  #
  # Put the Storybook distribution artifact onto the S3 origin.
  #
  dist_storybook:
    name: "Distribute Storybook"
    needs:
      - build_storybook
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      #
      # Step 1
      # Download CDN artifact and merge version artifact into the same folder
      #
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: storybook-dist
          path: storybook-dist

      #
      # Step 2
      # Set up AWS CLI
      #
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      #
      # Step 3
      # Replace 'latest' folder's content
      #
      - name: Replace latest
        working-directory: ${{steps.download.outputs.download-path}}
        run: aws s3 sync . s3://${{ secrets.S3_ORIGIN }}/storybook/latest --delete

  #
  # Put the homepage distribution artifact onto the S3 origin.
  #
  dist_homepage:
    name: "Distribute Homepage"
    needs:
      - build_homepage
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      #
      # Step 1
      # Download CDN artifact and merge version artifact into the same folder
      #
      - name: Download all workflow artifacts
        uses: actions/download-artifact@v2
        id: download
        with:
          name: homepage-dist
          path: homepage-dist
      - name: Download version artifacts
        uses: actions/download-artifact@v2
        with:
          path: homepage-dist

      #
      # Step 2
      # Set up AWS CLI
      #
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      #
      # Step 3
      # Create versioned release in S3
      #
      # WARNING BEFORE UPDATING CONFIG
      # The sync --delete has the power to remove everything from the bucket. Please try --dryrun before committing an
      # update!!!
      #
      - name: Replace homepage and it's assets
        working-directory: ${{steps.download.outputs.download-path}}
        run: aws s3 sync . s3://${{ secrets.S3_ORIGIN }}/ --exclude "cdn/*" --exclude "storybook/*" --exclude="error.html" --delete

  #
  # Clear the CloudFront cache.
  #
  clear_cache:
    name: "Clear CloudFront Cache"
    needs:
      - dist_homepage
      - dist_cdn
      - dist_storybook
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      #
      # Step 1
      # Set up AWS CLI
      #
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PIPELINE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PIPELINE_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      #
      # Step 2
      # Replace latest and invalid CloudFront's catch of latest
      #
      - name: Refesh CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/storybook/latest/*" "/cdn/latest/*" "/index.html"
